'use client'

import { useState } from 'react'

type Order = { id: string; customerName: string; customerEmail: string; total: number; status: string; createdAt: Date | string }
type Tab = 'dashboard' | 'orders' | 'products' | 'memes' | 'customers' | 'payments' | 'support' | 'settings'
const tabs: Array<[Tab, string]> = [['dashboard', 'Overview'], ['orders', 'Orders'], ['products', 'Products'], ['memes', 'Memes'], ['customers', 'Customers'], ['payments', 'Payments'], ['support', 'Support'], ['settings', 'Settings']]
const transitions: Record<string, string[]> = { pending: ['confirmed', 'cancelled'], confirmed: ['processing', 'cancelled'], processing: ['shipped'], shipped: ['delivered'], delivered: [], cancelled: [] }

export function AdminOperations({ initialOrders }: { initialOrders: Order[] }) {
  const [tab, setTab] = useState<Tab>('dashboard')
  const [orders, setOrders] = useState(initialOrders)
  const [status, setStatus] = useState('')
  const metrics = { revenue: orders.reduce((sum, order) => sum + order.total, 0), pending: orders.filter((order) => order.status === 'pending').length, production: orders.filter((order) => ['confirmed', 'processing'].includes(order.status)).length, shipped: orders.filter((order) => order.status === 'shipped').length, delivered: orders.filter((order) => order.status === 'delivered').length }
  async function updateOrder(id: string, nextStatus: string) { setStatus('Saving order state…'); const response = await fetch('/api/admin/orders', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id, status: nextStatus }) }); if (!response.ok) { setStatus('That status transition is not allowed.'); return } setOrders((current) => current.map((order) => order.id === id ? { ...order, status: nextStatus } : order)); setStatus('Order state saved.') }
  return <div className="admin-console"><nav className="admin-tabs" aria-label="Admin sections">{tabs.map(([key, label]) => <button type="button" key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{label}</button>)}</nav>{tab === 'dashboard' && <section><div className="admin-stat-grid"><article className="admin-stat admin-stat-yellow"><strong>{orders.length}</strong><span>Total orders</span></article><article className="admin-stat"><strong>₹{(metrics.revenue / 100).toLocaleString('en-IN')}</strong><span>Captured revenue</span></article><article className="admin-stat"><strong>{metrics.pending}</strong><span>Pending action</span></article><article className="admin-stat"><strong>{metrics.production}</strong><span>In production</span></article><article className="admin-stat"><strong>{metrics.shipped}</strong><span>Shipped</span></article><article className="admin-stat"><strong>{metrics.delivered}</strong><span>Delivered</span></article></div><div className="admin-alert"><b>OPERATIONS STATUS</b><p>Payment and fulfillment adapters are ready for Cashfree and Merch Factory. Live credentials are not connected yet, so no customer is charged or sent to production.</p></div></section>}{tab === 'orders' && <section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">ORDER MANAGEMENT</p><h2>Every order,<br /><em>under control.</em></h2></div><span>{orders.length} recorded</span></div>{orders.length ? orders.map((order) => <article className="admin-order-row" key={order.id}><div><b>{order.id}</b><strong>{order.customerName}</strong><small>{order.customerEmail}</small></div><div><b>₹{(order.total / 100).toLocaleString('en-IN')}</b><small>{new Date(order.createdAt).toLocaleDateString('en-IN')}</small></div><label className="admin-status-label">Status<select value={order.status} onChange={(event) => updateOrder(order.id, event.target.value)} aria-label={`Status for ${order.id}`}><option value={order.status}>{order.status}</option>{(transitions[order.status] ?? []).map((next) => <option value={next} key={next}>{next}</option>)}</select></label></article>) : <p className="admin-empty-copy">No orders yet. Secure order creation is ready for the checkout adapter.</p>}{status && <p className="admin-feedback" role="status">{status}</p>}</section>}{['products', 'memes', 'customers', 'payments', 'support', 'settings'].includes(tab) && <section className="admin-panel admin-coming-soon"><p className="eyebrow">{tab.toUpperCase()}</p><h2>{tab === 'memes' ? 'Meme library.' : tab === 'products' ? 'Catalog control.' : tab === 'customers' ? 'Customer records.' : tab === 'payments' ? 'Payment ledger.' : tab === 'support' ? 'Support desk.' : 'System settings.'}</h2><p>This operating area is scaffolded and protected. Connect the corresponding database records and provider adapter when the launch credentials are ready.</p></section>}</div>
}
