'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowDown, ArrowRight, Check, Menu, Minus, Plus, ShoppingBag, X } from 'lucide-react'

type MemeTier = 'COMMON BALL KNOWLEDGE' | 'MID BALL KNOWLEDGE' | 'ELITE BALL KNOWLEDGE'
type StockStatus = 'available' | 'out-of-stock' | 'not-configured'
type PricingRule = 'flat'

type Meme = { id: string; name: string; tier: MemeTier; artwork: string; licensing: 'ORIGINAL' | 'LICENSED' | 'PERMISSION_GRANTED' | 'REVIEW_REQUIRED' }
type Variant = { id: string; color: string; hex: string; sizes: string[]; stock: Record<string, StockStatus>; printroveProductId?: string; printroveVariantIds?: Record<string, string> }
type Garment = { id: string; name: string; short: string; basePrice: number; gsm: string; description: string; fit: string; care: string; pricingRule: PricingRule; supportsMemes: boolean; variants: Variant[]; compatibleMemeIds: string[] }
type CartItem = { garmentId: string; variantId: string; memeId?: string; size: string; quantity: number }

const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Image-9F22B585-1kqlezpaxC4jw8agJdCKAv0KH87Ucf.jpeg'
const instagramUrl = 'https://www.instagram.com/hilolwear/'
const memes: Meme[] = [
  { id: 'm01', name: 'one more reel', tier: 'COMMON BALL KNOWLEDGE', artwork: 'ONE MORE REEL', licensing: 'ORIGINAL' },
  { id: 'm02', name: 'camera roll evidence', tier: 'MID BALL KNOWLEDGE', artwork: 'DELETE NOTHING', licensing: 'ORIGINAL' },
  { id: 'm03', name: 'algorithmic damage', tier: 'MID BALL KNOWLEDGE', artwork: 'THE FEED NEVER ENDS', licensing: 'ORIGINAL' },
  { id: 'm04', name: 'offline pending', tier: 'ELITE BALL KNOWLEDGE', artwork: 'TOUCH GRASS LATER', licensing: 'ORIGINAL' },
  { id: 'm05', name: 'bad decision club', tier: 'ELITE BALL KNOWLEDGE', artwork: 'GOOD OUTFIT THOUGH', licensing: 'ORIGINAL' },
]
const productSeed: Array<Omit<Garment, 'variants' | 'compatibleMemeIds'> & { colors: [string, string][]; sizes: string[] }> = [
  { id: 'round-neck', name: 'Round Neck Tee', short: 'Round Neck Tee', basePrice: 469, gsm: '180 GSM', description: 'A lightweight, breathable, pre-shrunk cotton-based tee with a softer hand feel.', fit: 'Standard / Regular Fit', care: 'Wash inside out, cold.', pricingRule: 'flat', supportsMemes: true, colors: [['Black', '#111111'], ['White', '#f4f4f0']], sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'] },
  { id: 'normal-oversized-tee', name: 'Normal Oversized Tee', short: 'Normal Oversized Tee', basePrice: 579, gsm: '220 GSM', description: 'A structured oversized streetwear tee with a heavier everyday feel.', fit: 'Oversized / Drop-Shoulder', care: 'Wash inside out, cold.', pricingRule: 'flat', supportsMemes: true, colors: [['Black', '#111111'], ['Bone', '#ded8c9']], sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'] },
  { id: 'premium-oversized-tee', name: 'Premium Oversized Tee', short: 'Premium Oversized Tee', basePrice: 629, gsm: '240 GSM', description: 'Heavyweight construction with a thicker, structured premium oversized feel.', fit: 'Oversized / Drop-Shoulder', care: 'Wash inside out, cold.', pricingRule: 'flat', supportsMemes: true, colors: [['Black', '#111111'], ['Grey', '#777777']], sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'] },
  { id: 'premium-acid-wash-oversized-tee', name: 'Premium Acid Wash Oversized Tee', short: 'Premium Acid Wash Oversized Tee', basePrice: 679, gsm: '240 GSM', description: 'A heavyweight oversized tee with a washed streetwear appearance and unique acid-wash finish.', fit: 'Oversized / Drop-Shoulder', care: 'Wash inside out, cold.', pricingRule: 'flat', supportsMemes: true, colors: [['Charcoal', '#3a3a38'], ['Stone', '#8c877a']], sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'] },
]
const commonVariant = (id: string, colors: [string, string][], sizes: string[]): Variant[] => colors.map(([color, hex], index) => ({ id: `${id}-color-${index + 1}`, color, hex, sizes, stock: Object.fromEntries(sizes.map((size) => [size, 'not-configured'])) as Record<string, StockStatus> }))
const garments: Garment[] = productSeed.map(({ colors, sizes, ...garment }) => ({ ...garment, variants: commonVariant(garment.id, colors, sizes), compatibleMemeIds: garment.supportsMemes ? memes.map((meme) => meme.id) : [] }))
const PRICE_TABLES: Record<PricingRule, Record<string, number>> = { flat: { S: 0 } }
function priceFor(garment: Garment, size: string) { return garment.pricingRule === 'flat' ? garment.basePrice : PRICE_TABLES[garment.pricingRule][size] ?? garment.basePrice }
function findGarment(id: string) { return garments.find((garment) => garment.id === id) ?? garments[0] }
function findMeme(id?: string) { return memes.find((meme) => meme.id === id) }
function ProductVisual({ garment, variant, meme, large = false }: { garment: Garment; variant: Variant; meme?: Meme; large?: boolean }) { return <div className={`product-visual ${large ? 'product-visual-large' : ''}`} style={{ background: variant.hex }}><div className="visual-noise" /><span className="visual-brand">hi lol</span><span className="visual-meme">{meme?.artwork ?? (garment.supportsMemes ? 'SELECT A MEME' : 'PLAIN / NO MEME')}</span><div className="tee-shape"><div className="tee-neck" /><div className="tee-print">{meme ? meme.artwork.split(' ')[0] : 'LOL'}<br /><small>{meme ? 'IRL' : 'WEAR'}</small></div></div><span className="visual-label">{garment.gsm} / {variant.color}</span></div> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [cartOpen, setCartOpen] = useState(false)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [selectedVariantId, setSelectedVariantId] = useState('')
  const [selectedMemeId, setSelectedMemeId] = useState<string | undefined>(memes[0].id)
  const [selectedSize, setSelectedSize] = useState('S')
  const [cart, setCart] = useState<CartItem[]>([])
  const [level, setLevel] = useState<MemeTier>('MID BALL KNOWLEDGE')
  const [faq, setFaq] = useState<number | null>(null)
  const [cartReady, setCartReady] = useState(false)
  const [shopFilter, setShopFilter] = useState('ALL')
  const selected = selectedId ? findGarment(selectedId) : null
  useEffect(() => { try { const savedCart = window.localStorage.getItem('hilol-cart'); if (savedCart) setCart(JSON.parse(savedCart) as CartItem[]) } catch { setCart([]) } finally { setCartReady(true) } }, [])
  useEffect(() => { if (cartReady) window.localStorage.setItem('hilol-cart', JSON.stringify(cart)) }, [cart, cartReady])
  useEffect(() => {
    if (typeof window === 'undefined') return
    window.history.scrollRestoration = 'auto'
  }, [])
  const selectedVariant = selected?.variants.find((variant) => variant.id === selectedVariantId) ?? selected?.variants[0]
  const selectedMeme = findMeme(selectedMemeId)
  const cartTotal = useMemo(() => cart.reduce((total, item) => total + priceFor(findGarment(item.garmentId), item.size) * item.quantity, 0), [cart])
  function openProduct(garment: Garment) { setSelectedId(garment.id); setSelectedVariantId(garment.variants[0].id); setSelectedSize(garment.variants[0].sizes[0]); setSelectedMemeId(garment.supportsMemes ? garment.compatibleMemeIds[0] : undefined) }
  function addToCart() { if (!selected || !selectedVariant) return; setCart((items) => [...items, { garmentId: selected.id, variantId: selectedVariant.id, size: selectedSize, memeId: selectedMemeId, quantity: 1 }]); setSelectedId(null) }
  function beginCheckout() { const checkoutItems = cart.map((item, index) => { const garment = findGarment(item.garmentId); const variant = garment.variants.find((entry) => entry.id === item.variantId) ?? garment.variants[0]; return { id: `${item.garmentId}-${item.variantId}-${item.size}-${index}`, garmentId: item.garmentId, variantId: item.variantId, name: garment.name, size: item.size, color: variant.color, meme: findMeme(item.memeId)?.name ?? 'Plain', quantity: item.quantity, price: priceFor(garment, item.size) } }); window.localStorage.setItem('hilol-checkout', JSON.stringify(checkoutItems)); window.location.href = '/checkout' }
  function changeQuantity(index: number, delta: number) { setCart((items) => items.flatMap((item, itemIndex) => itemIndex === index && item.quantity + delta <= 0 ? [] : itemIndex === index ? [{ ...item, quantity: item.quantity + delta }] : [item])) }
  const goToShop = (item: string) => { setShopFilter(item === 'SHOP' ? 'ALL' : item); document.getElementById('shop')?.scrollIntoView({ behavior: 'auto', block: 'start' }) }
  const visibleGarments = garments.filter((garment) => shopFilter === 'ALL' || shopFilter === 'OVERSIZED' && ['normal-oversized-tee', 'premium-oversized-tee', 'premium-acid-wash-oversized-tee'].includes(garment.id))
  return <main id="top" className="site-shell"><header className="site-nav"><button className="menu-button" aria-label="Open menu" onClick={() => setMenuOpen(true)}><Menu size={22} /></button><a className="logo" href="#top"><img src={logoUrl} alt="hi lol wear your humor" /></a><nav className="desktop-nav">{['SHOP', 'OVERSIZED', 'ABOUT'].map((item) => item === 'ABOUT' ? <a key={item} href="/about">{item}</a> : <a key={item} href="#shop" onClick={(event) => { event.preventDefault(); goToShop(item) }}>{item}</a>)}</nav><div className="nav-actions"><a href="/sign-in" className="track-link">SIGN IN</a><a href="/track" className="track-link">TRACK ORDER</a><button className="cart-button" onClick={() => setCartOpen(true)} aria-label="Open cart"><ShoppingBag size={19} /><span>{cart.reduce((total, item) => total + item.quantity, 0)}</span></button></div></header>
  <div className={`mobile-menu ${menuOpen ? 'is-open' : ''}`} aria-hidden={!menuOpen}><button className="close-button" onClick={() => setMenuOpen(false)} aria-label="Close menu"><X /></button><span className="menu-kicker">THE MENU, BUT MAKE IT LOUD</span>{['SHOP', 'OVERSIZED', 'ABOUT'].map((item, index) => item === 'ABOUT' ? <a key={item} href="/about" onClick={() => setMenuOpen(false)}>{item}<ArrowRight /></a> : <a key={item} href="#shop" onClick={(event) => { event.preventDefault(); setMenuOpen(false); goToShop(item) }}>{item}<ArrowRight /></a>)}<a className="menu-track" href="/track">TRACK ORDER <ArrowRight /></a></div>
  <section className="hero-section"><div className="hero-copy"><span className="sticker sticker-top">INDIAN MEME WEAR</span><h1>hi<br /><span>lol</span></h1><p className="hero-tagline">wear your humor</p><p className="hero-sub">you were going to scroll anyway. make it a fit.</p><div className="hero-actions"><a className="button button-black" href="#shop">SHOP THE DROP <ArrowRight size={17} /></a><a className="scroll-link" href="#brainrot">SCROLL THE BRAINROT <ArrowDown size={16} /></a></div></div><div className="hero-art"><img className="hero-logo-art" src={logoUrl} alt="hi lol. wear your humor" /><div className="hero-shirt"><div className="tee-neck" /><div className="tee-print">BRB<br /><small>BEING<br />ICONIC</small></div></div><span className="sticker sticker-corner">100%<br />UNSERIOUS</span></div><div className="hero-bottom"><span>SCROLL IF YOU DARE</span><span>↓</span><span>EST. 2026 / INDIA</span></div></section>
  <div className="static-strip">WEAR YOUR HUMOR <span>+</span> WEAR YOUR HUMOR <span>+</span> WEAR YOUR HUMOR</div>
  <section id="brainrot" className="brainrot-section section-pad"><div className="section-head"><span className="eyebrow">THE FEED</span><h2>SHOP THE<br /><em>BRAINROT</em></h2><p>Original internet-native artwork for when the feed has already cooked you.</p></div><div className="level-switcher">{(['COMMON BALL KNOWLEDGE', 'MID BALL KNOWLEDGE', 'ELITE BALL KNOWLEDGE'] as MemeTier[]).map((item, index) => <button className={level === item ? 'active' : ''} key={item} onClick={() => setLevel(item)}><span className="tier-name">{item}</span><small>{index === 0 ? 'you know this one. don’t lie.' : index === 1 ? 'ts has lore. unfortunately.' : 'gng, the feed owns you.'}</small></button>)}</div></section>
  <section id="shop" className="featured-section section-pad"><div className="section-head row-head"><div><span className="eyebrow">THE DROP</span><h2>THE<br /><em>DROP</em></h2></div><span className="text-link">4 GARMENTS <ArrowRight size={16} /></span></div><div className="shop-filters" aria-label="Shop categories">{['ALL', 'OVERSIZED'].map((filter) => <button key={filter} className={shopFilter === filter ? 'active' : ''} onClick={() => setShopFilter(filter)}>{filter}</button>)}</div><div className="product-grid">{visibleGarments.map((garment, index) => <article className="product-card" key={garment.id} onClick={() => openProduct(garment)}><ProductVisual garment={garment} variant={garment.variants[0]} meme={garment.supportsMemes ? memes[0] : undefined} /><div className="product-info"><h3>{garment.name}</h3><strong>₹{garment.basePrice}</strong></div><div className="product-hover">OPEN GARMENT <ArrowRight size={17} /></div></article>)}</div></section>
  <section id="oversized" className="fit-section"><div className="fit-copy"><span className="eyebrow">FEED CHECK</span><h2>HOW<br /><em>CHRONICALLY<br />ONLINE?</em></h2><p>Pick your current level of internet damage. No judgment. The slider is already judging.</p><a className="button button-yellow" href="#shop">FIND YOUR MEME <ArrowRight size={16} /></a></div><div className="fit-art"><input className="online-slider" type="range" min="1" max="3" value={level === 'COMMON BALL KNOWLEDGE' ? 1 : level === 'MID BALL KNOWLEDGE' ? 2 : 3} onChange={(event) => setLevel((['COMMON BALL KNOWLEDGE', 'MID BALL KNOWLEDGE', 'ELITE BALL KNOWLEDGE'] as MemeTier[])[Number(event.target.value) - 1])} aria-label="How chronically online are you" /><div className="fit-scale"><span>CASUALLY ONLINE</span><span>INSTA HUMOR</span><span>THE FEED OWNS YOU</span></div><p className="fit-note">{level === 'COMMON BALL KNOWLEDGE' ? 'you still go outside sometimes.' : level === 'MID BALL KNOWLEDGE' ? 'the group chat has evidence.' : 'your screen time report is not invited.'}</p></div></section>
  <section id="quality" className="quality-section section-pad"><div className="quality-title"><span className="eyebrow">BUILT FOR THE MEME.</span><h2>WEAR THE<br /><em>JOKE<br />PROPERLY.</em></h2></div><div className="quality-grid"><div className="quality-intro"><p>Different fits. Different weights. Same commitment to wearing the joke properly.</p><a href="#quality-details" className="button button-yellow">SEE THE DETAILS <ArrowDown size={16} /></a></div><div id="quality-details" className="gsm-card"><span>FABRIC WEIGHT</span><div className="gsm-list">{[['180', 'STANDARD FIT'], ['220', 'OVERSIZED'], ['240', 'PREMIUM OVERSIZED'], ['240', 'ACID WASH']].map(([weight, label]) => <div key={label}><b>{weight}</b><small>{label}</small></div>)}</div></div><div className="detail-list"><div><b>PRINT</b><span>Industrial High-Density DTF printing delivers sharp graphics with a smooth, flexible finish.</span></div><div><b>QUALITY</b><span>Pre-shrunk specifications, softer hand feel, reduced pilling, heat curing, and production quality checks.</span></div><div><b>LABEL</b><span>Custom HILOL tagless soft-touch heat-transfer label with a smooth, non-itchy feel.</span></div><div><b>DELIVERY</b><span>Standard delivery is estimated at 4–5 days. Remote locations may take longer.</span></div></div></div></section>
  <section className="faq-section section-pad"><div className="section-head"><span className="eyebrow">IMPORTANT BUT FUN</span><h2>FAQ, BUT<br /><em>MAKE IT LOUD</em></h2></div>{['Do you offer COD?', 'Is express delivery included?', 'Can I return my order if I change my mind?', 'What if something arrives wrong?'].map((question, index) => <div className="faq-row" key={question}><button onClick={() => setFaq(faq === index ? null : index)}><b>{question}</b>{faq === index ? <Minus /> : <Plus />}</button>{faq === index && <div className="faq-answer is-open"><p>{index === 0 ? 'Yes. COD is available with a ₹35 COD fee. ₹80 is paid upfront through UPI and the remaining amount is paid at delivery.' : index === 1 ? 'No. Standard Delhivery Surface delivery is included. BlueDart Express Air is an optional ₹40 upgrade and may arrive approximately 1–2 days faster.' : index === 2 ? 'No. Change-of-mind returns are not accepted for made-to-order products. Please check the size guide before ordering.' : 'Contact HILOL Support within 24 hours of delivery with your order number and required evidence. Verified issues may qualify for a free replacement.'}</p></div>}</div>)}</section>
  <section className="final-cta"><h2>YEAH GNG,<br /><em>YOU DEF NEED TS.</em></h2><a className="button button-yellow" href="#shop">FIX YOUR WARDROBE <ArrowRight size={17} /></a><span className="final-small">or don’t. stay cooked.</span></section>
  <footer className="site-footer"><div className="footer-brand"><a className="logo" href="#top"><img src={logoUrl} alt="hi lol wear your humor" /></a><p>wear your humor</p><span className="footer-note">premium meme wear from india.</span></div><div className="footer-links"><div><b>SHOP</b><a href="#shop" onClick={(event) => { event.preventDefault(); goToShop('SHOP') }}>All garments</a><a href="#shop" onClick={(event) => { event.preventDefault(); goToShop('OVERSIZED') }}>Oversized</a></div><div><b>HELP</b><a href="/track">Track order</a><a href="/support">Support</a><a href="/refund">Refunds</a><a href="/cancellation">Cancellation</a><a className="instagram-link" href={instagramUrl} target="_blank" rel="noreferrer" aria-label="HILOL on Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" strokeWidth="2" /><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" strokeWidth="2" /><circle cx="17.5" cy="6.5" r="1" fill="currentColor" /></svg></a></div><div><b>LEGAL</b><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/shipping">Shipping</a></div></div><div className="footer-bottom"><span>© 2026 hi lol</span></div></footer>
  {selected && selectedVariant && <div className="modal-backdrop" onClick={() => setSelectedId(null)}><div className="product-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelectedId(null)} aria-label="Close product"><X /></button><ProductVisual garment={selected} variant={selectedVariant} meme={selectedMeme} large /><div className="modal-content"><span className="product-category">{selected.short}</span><h2>{selected.name}</h2><p className="wear-this">WEAR THIS IF...</p><p>{selected.description}</p><div className="option-block"><span>COLOR</span><div className="color-row">{selected.variants.map((variant) => <button key={variant.id} className={selectedVariant.id === variant.id ? 'selected' : ''} onClick={() => setSelectedVariantId(variant.id)}>{variant.color}</button>)}</div></div><div className="option-block"><span>CHOOSE SIZE</span><div className="size-row">{selectedVariant.sizes.map((size) => <button key={size} className={selectedSize === size ? 'selected' : ''} onClick={() => setSelectedSize(size)}>{size}</button>)}</div></div><div className="live-price"><span>FINAL HILOL PRICE / {selectedSize}</span><strong>₹{priceFor(selected, selectedSize)}</strong></div><button className="button button-black full" onClick={addToCart}>ADD TO CART <ArrowRight size={16} /></button></div></div></div>}
  {cartOpen && <div className="cart-drawer-wrap" onClick={() => setCartOpen(false)}><aside className="cart-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-head"><span>YOUR CART ({cart.reduce((total, item) => total + item.quantity, 0)})</span><button onClick={() => setCartOpen(false)} aria-label="Close cart"><X /></button></div>{cart.length === 0 ? <div className="empty-cart"><span className="cart-face">YOUR CART</span><h2>JUS ADD SOMETHING<br /><em>TO CART BROCHACHO.</em></h2></div> : <><div className="cart-items">{cart.map((item, index) => { const garment = findGarment(item.garmentId); const variant = garment.variants.find((entry) => entry.id === item.variantId) ?? garment.variants[0]; return <div className="cart-item" key={`${item.garmentId}-${item.variantId}-${item.size}`}><div className="cart-thumb" style={{ background: variant.hex }} /><div className="cart-item-copy"><b>{garment.name}</b><small>{variant.color} / {item.size}</small><div className="qty"><button onClick={() => changeQuantity(index, -1)}>-</button><span>{item.quantity}</span><button onClick={() => changeQuantity(index, 1)}>+</button></div></div><strong>₹{priceFor(garment, item.size) * item.quantity}</strong></div> })}</div><div className="cart-summary"><div><span>SHIPPING</span><b>INCLUDED</b></div><div className="cart-total"><span>TOTAL</span><b>₹{cartTotal}</b></div><button className="button button-black full" onClick={beginCheckout}>CHECKOUT <ArrowRight size={16} /></button></div></>}</aside></div>}
  </main>
}
