export type LegalSection = { title: string; body: string }

export const legalContent = {
  terms: {
    eyebrow: 'LEGAL / TERMS', title: 'TERMS OF SERVICE.', lede: 'Wear your humor responsibly. Last updated: 2026.', sections: [
      ['About these Terms', 'These Terms govern access to and use of the HILOL website, including browsing, purchasing products, contacting HILOL, and using website features. By using HILOL or placing an order, you confirm that you have read, understood, and agree to these Terms.'],
      ['The HILOL website', 'HILOL provides an online storefront where customers can browse products, view designs, sizes, colours, specifications, use the size guide, add products to a cart, place orders, make payments, access order information, track eligible orders, contact HILOL, and access policies.'],
      ['Products and availability', 'HILOL makes reasonable efforts to provide accurate information about garment type, fabric weight, fit, sizes, colours, designs, print information, care, pricing, and availability. Minor differences in colour, lighting, screens, photography, and printing do not automatically constitute a defect. Products and variants remain subject to availability.'],
      ['Made-to-order products and sizing', 'Certain products are prepared after an order is placed and may not be modifiable once production begins. Customers are responsible for selecting the appropriate size and should check the specific garment size chart before ordering. Standard-fit and oversized garments use different measurements.'],
      ['Customer information and orders', 'Customers are responsible for accurate name, phone, email, address, PIN code, product, design, colour, size, quantity, and delivery information. Before submitting an order, review the complete product, delivery, contact, and payable-amount details.'],
      ['Pricing, taxes and payment', 'Prices are in Indian Rupees. Where applicable, GST and standard shipping costs are incorporated into displayed prices. Optional services or charges are shown before confirmation. Payment methods may vary, and online orders generally enter fulfillment after successful payment confirmation.'],
      ['Cancellation, returns and shipping', 'Cancellation is governed by the Cancellation Policy and is limited to 60 minutes before printing begins. Returns, replacements, defects, refunds, shipping, and delivery are governed by their dedicated HILOL policies.'],
      ['Intellectual property and acceptable use', 'HILOL and its licensors retain rights in the HILOL name, logos, artwork, designs, photographs, writing, animations, interface, and website. Purchasing a physical product does not grant permission to reproduce or commercially reuse HILOL designs. Do not misuse the website, submit unlawful content, interfere with operations, access another customer’s information, or attempt to compromise security.'],
      ['Privacy and third parties', 'Personal information is handled under the Privacy Policy. HILOL may rely on third parties for payments, hosting, communications, logistics, tracking, analytics, security, and infrastructure; those providers may have their own terms and policies.'],
      ['Disclaimers and applicable law', 'HILOL provides the website on an available basis and makes reasonable efforts to maintain accurate information. Delivery estimates are not guarantees. Mandatory consumer rights remain unaffected. These Terms operate under applicable Indian law.'],
    ] as LegalSection[]
  },
  privacy: {
    eyebrow: 'LEGAL / PRIVACY', title: 'PRIVACY, WITHOUT THE WEIRDNESS.', lede: 'At HILOL, we collect and use information mainly to get your order to you and help when something goes wrong. Last updated: 2026.', sections: [
      ['What we collect', 'Depending on how you use HILOL, we may collect your name, phone number, email address, shipping and billing information, order details including products, sizes, colours, quantities and status, payment transaction information, support messages, account information, and information voluntarily provided through forms or reviews.'],
      ['Why we use it', 'We use information to process and fulfill orders, communicate about orders, arrange printing, packaging and delivery, provide support, handle cancellations and refunds, verify transactions, prevent fraud, improve the website, communicate service information, comply with legal requirements, and protect HILOL and its customers.'],
      ['Payments', 'Payments may be processed through Cashfree or another available provider. HILOL does not intentionally store full card numbers, card security codes, UPI PINs, banking passwords, or payment passwords. We may receive payment status, transaction identifiers, and related order information.'],
      ['Who we share information with', 'We may share information reasonably necessary with payment providers, fulfillment and production partners, courier providers, hosting and technology providers, support providers, security services, and authorities where disclosure is required or permitted by law. We do not sell personal information.'],
      ['Cookies, security and retention', 'HILOL may use cookies, local storage, analytics, and similar technologies for essential functionality, preferences, performance, and understanding website usage. We use reasonable safeguards such as HTTPS, access controls, limited access, authentication, and operational security. Information is retained only as reasonably necessary for orders, support, disputes, fraud prevention, and legal, tax, accounting, or regulatory requirements.'],
      ['Your choices', 'Subject to applicable law and retention requirements, you may contact HILOL to request access, correction, deletion where legally available, or information about how your personal information is handled.'],
      ['Children, legal requirements and changes', 'HILOL is not specifically directed toward children. We may use or disclose information to comply with law, respond to lawful requests, enforce policies, investigate fraud, and protect rights, safety, and property. We may update this policy and the Last updated date when practices or legal requirements change.'],
      ['Contact us', 'For privacy questions or requests, contact HILOL Support through the official contact details available on the website.'],
    ] as LegalSection[]
  },
  shipping: {
    eyebrow: 'POLICY / SHIPPING', title: 'SHIPPING. GET IT. WEAR IT.', lede: 'Standard delivery is included on eligible orders, with an optional express upgrade at checkout. Last updated: 2026.', sections: [
      ['Standard delivery', 'Standard delivery is included in the displayed product price for eligible orders. Orders use Delhivery Surface. Estimated delivery is 4–5 days after dispatch, depending on destination and serviceability. Remote or restricted locations may take longer.'],
      ['Express delivery', 'Express is an optional ₹40 upgrade where serviceability permits. Express orders use BlueDart Express Air and may arrive approximately 1–2 days faster than Standard. Selecting Express does not guarantee a particular date or time.'],
      ['Processing and tracking', 'Delivery estimates refer to the courier period and do not necessarily begin when an order is placed. Processing, production, packing, and courier pickup may take additional time. Tracking is provided when available and may take time to activate.'],
      ['Address and delivery attempts', 'Check name, phone number, house or building, street, city, state, and PIN code carefully. Incorrect or incomplete information can cause delivery problems. Keep your phone available and cooperate with reasonable delivery requirements. Failed attempts, refused COD orders, and return-to-origin procedures may apply.'],
      ['Delays, remote locations and damaged packages', 'Weather, holidays, high volumes, traffic, remote serviceability, incorrect information, unsuccessful attempts, natural events, government restrictions, and other circumstances can affect estimates. If a package appears damaged, document it and contact Support.'],
      ['Lost or undelivered orders', 'If an order has not arrived within a reasonable period after the expected window, contact Support. HILOL may work with the courier to investigate, with the applicable remedy handled under the Refund and Replacement Policy and applicable law.'],
      ['Express refunds and estimates', 'Express is optional and does not automatically guarantee compensation or a refund of its fee after a courier delay. All timelines are estimates, not guarantees.'],
      ['Contact Support', 'For delivery help, include your order number, name, phone or email, and tracking information if available.'],
    ] as LegalSection[]
  },
  refunds: {
    eyebrow: 'POLICY / RETURNS', title: 'REFUNDS. WHEN SOMETHING ACTUALLY GOES WRONG.', lede: 'HILOL products are made to order. We do not accept ordinary returns or exchanges for changed minds or wrong-size selections. If we make a fulfillment or manufacturing mistake, we will make it right. Last updated: 2026.', sections: [
      ['Cancellation window', 'You may request cancellation within 60 minutes of placing an order, provided printing has not begun. After 60 minutes or once printing begins, the order cannot ordinarily be cancelled or changed.'],
      ['When a replacement may be available', 'Contact HILOL within 24 hours of delivery if an item is damaged, genuinely defective, incorrectly printed, the wrong design, the wrong product, the wrong size or colour due to HILOL fulfillment error, or missing. Verified issues may receive a replacement or reprint at no additional product cost.'],
      ['Unboxing evidence', 'For certain claims, HILOL may require a continuous, uncut 360° unboxing video beginning with the sealed package, showing the shipping label, opening, contents being removed, and complete contents. Claims requiring this evidence should be submitted within 24 hours of delivery.'],
      ['What is not eligible', 'Change of mind, wrong size, wrong colour, wrong design, wrong quantity, normal wear, incorrect care, misuse, customer alterations, customer-caused damage, and minor variations within reasonable industry tolerances are not normally eligible.'],
      ['Size selection and manufacturing variations', 'Compare the applicable size chart with a garment you own before ordering. A customer-selected wrong size is not ordinarily a fulfillment error. Small variations in measurements, placement, colour appearance, or other characteristics do not automatically constitute a defect.'],
      ['Courier damage and lost orders', 'Document damaged packages and contact Support. If an order has not arrived within a reasonable period after the expected delivery window, contact Support so HILOL can investigate with the delivery provider.'],
      ['Refunds and return shipping', 'Replacement or reprint is the normal remedy for verified made-to-order issues. Where a monetary refund is required or appropriate under law or the circumstances, it will be processed through the applicable payment method. HILOL may arrange or cover return shipping for verified HILOL errors.'],
      ['How to make a claim', 'Contact Support within 24 hours for damaged, defective, incorrectly printed, wrong, or missing items. Include your order number, contact details, issue description, photographs, and an uncut video if requested. Keep the product and packaging until review.'],
      ['Applicable law and support', 'Claims are reviewed individually. This policy is intended to operate consistently with applicable Indian consumer-protection laws, and mandatory rights remain unaffected.'],
    ] as LegalSection[]
  },
  cancellation: {
    eyebrow: 'POLICY / CANCELLATION', title: 'CANCELLATION. BEFORE IT GOES INTO PRODUCTION.', lede: 'HILOL products are made to order, so orders can enter production quickly. The cancellation window is intentionally short. Last updated: 2026.', sections: [
      ['60-minute cancellation window', 'You may request cancellation within 60 minutes of placing an order, provided printing has not begun. After 60 minutes or once printing has begun, the order generally cannot be cancelled or changed, including product, design, size, colour, quantity, delivery information, or other details.'],
      ['Cancellation is a request', 'Submitting a cancellation request does not automatically cancel an order. Cancellation is complete only after HILOL confirms it. Until confirmation, the order remains active.'],
      ['How to request cancellation', 'Contact HILOL Support through the Support link and provide the order number, name used for the order, phone or email associated with it, and a clear cancellation request. Contact Support as soon as possible.'],
      ['COD orders', 'For Cash on Delivery orders, ₹80 is paid upfront and the remaining amount at delivery. If an eligible cancellation is confirmed within 60 minutes and before printing, the full ₹80 upfront payment will be refunded and no remaining COD amount will be collected.'],
      ['Prepaid orders', 'For prepaid orders, an eligible cancellation confirmed within the 60-minute window will be processed for the applicable refund. Processing times may vary by payment provider or financial institution.'],
      ['After the cancellation window', 'Once the window has passed or printing has begun, HILOL generally cannot cancel or modify an order. Contact Support immediately if you notice an error, but changes are not guaranteed.'],
      ['HILOL cancellations and refused delivery', 'HILOL may cancel for availability, technical or pricing errors, unusable information, an unserviceable location, payment problems, suspected fraud, or circumstances beyond reasonable control. Refusing or ignoring delivery after fulfillment or transit does not count as cancellation.'],
      ['Applicable law', 'This policy is intended to operate consistently with applicable Indian consumer-protection laws. Mandatory rights remain unaffected.'],
    ] as LegalSection[]
  }
} as const
