export type LegalSection = { title: string; body: string }

const section = (title: string, body: string): LegalSection => ({ title, body })

export const legalContent = {
  terms: { eyebrow: 'LEGAL / TERMS', title: 'TERMS OF SERVICE.', lede: 'Wear your humor responsibly. Last updated: 2026.', sections: [
    section('1. About these Terms', 'These Terms form an agreement between you and HILOL regarding your use of the HILOL website and the purchase of products through it. “HILOL”, “we”, “us”, and “our” refer to HILOL. “You”, “your”, “customer”, and “user” refer to the person accessing the website or purchasing products.'),
    section('2. Acceptance of the Terms', 'By using the website or placing an order, you confirm that you have read, understood, and agree to comply with these Terms, that information you provide is accurate and complete, and that you will use HILOL only for lawful purposes. If you do not agree, stop using the website.'),
    section('3. Eligibility', 'You may use HILOL only where you are legally permitted to enter into an agreement and purchase products. Where required, a parent, guardian, or other legally authorised person should be involved.'),
    section('4. The HILOL Website', 'HILOL provides an online storefront for browsing products, designs, sizes, colours and specifications; using the size guide; adding products to a cart; placing orders; making payments; accessing order information; tracking eligible orders; contacting HILOL; and accessing policies. Features may be added, removed, modified, suspended, or discontinued.'),
    section('5. Website Availability', 'We make reasonable efforts to keep HILOL functional. The website may be unavailable because of maintenance, upgrades, technical problems, hosting or network failures, security incidents, provider outages, or circumstances beyond our reasonable control. Continuous availability and complete error-free operation are not guaranteed.'),
    section('6. Product Information', 'We make reasonable efforts to provide accurate product names, garment details, fabric weight, fit, sizes, colours, designs, images, print and care information, pricing, and availability. Minor differences caused by colour, lighting, photography, screens, or printing do not automatically constitute a defect.'),
    section('7. Availability and Made-to-Order Products', 'Products and variants are subject to availability and may change or be discontinued. Certain products are prepared after an order is placed and may enter a production process specific to your selections. They may not be modified or cancelled once production begins.'),
    section('8. Size Selection', 'Customers are responsible for choosing the appropriate size. Check the applicable chart for the specific garment before ordering. Standard-fit and oversized garments use different measurements, and sizes should not be assumed to match other brands or garment types.'),
    section('9. Customer Information and Orders', 'You are responsible for accurate name, phone, email, address, PIN code, product, design, colour, size, quantity, and delivery information. Review every order detail and the final payable amount before submitting an order.'),
    section('10. Order Acceptance', 'An acknowledgement or confirmation does not prevent HILOL from verifying payment, availability, serviceability, technical errors, suspected fraud, unusual activity, pricing, or operational limitations. If an order cannot reasonably be fulfilled, HILOL may contact you regarding an appropriate resolution.'),
    section('11. Pricing, Taxes and Payment', 'Prices are in Indian Rupees. Where applicable, GST and standard shipping costs are incorporated into the displayed price. Optional charges appear before confirmation. Payment methods may vary by location, eligibility, provider availability, and operational requirements. Online orders generally enter fulfillment after payment confirmation.'),
    section('12. Cash on Delivery', 'Where available, COD may be offered for eligible orders and serviceable locations. COD may carry a fee or upfront payment requirement shown at checkout. HILOL may restrict COD for reasonable fraud-prevention, serviceability, operational, or order-history reasons.'),
    section('13. Cancellation, Returns and Shipping', 'Cancellation is governed by the separate Cancellation Policy and is limited to 60 minutes before printing begins. Returns, replacements, refunds, shipping, and delivery are governed by their dedicated HILOL policies.'),
    section('14. Intellectual Property', 'The HILOL name, logos, brand identity, artwork, designs, photographs, illustrations, written content, animations, interface, icons, layouts, videos, and creative concepts belong to HILOL or the relevant rights holder. Buying a physical product does not transfer ownership of the underlying intellectual property or permission to reproduce it.'),
    section('15. Acceptable Use and Security', 'You must not use HILOL for unlawful activity, interfere with operations, introduce harmful code, attempt unauthorised access, access another customer’s information, impersonate anyone, submit fraudulent information, manipulate orders, abuse promotions, exploit vulnerabilities, interfere with payment systems, or overload infrastructure.'),
    section('16. Privacy and Third Parties', 'Personal information is handled under the Privacy Policy. HILOL may rely on payment, hosting, communications, logistics, tracking, analytics, security, and infrastructure providers. Third parties may have their own terms and policies.'),
    section('17. Website Content and Promotions', 'HILOL may offer discounts, promotional pricing, limited-time offers, or product-specific promotions with additional terms, eligibility requirements, usage limits, or expiry dates. We may correct obvious technical or pricing errors.'),
    section('18. Disclaimers and Liability', 'To the maximum extent permitted by law, HILOL provides the website and content on an “as available” basis. Delivery estimates are not guarantees. HILOL will not be liable for indirect, incidental, special, consequential, or similar losses to the extent legally permitted. Mandatory consumer rights remain unaffected.'),
    section('19. Events Beyond Control', 'HILOL is not responsible for delay or failure reasonably caused by natural disasters, severe weather, public emergencies, government restrictions, transport disruption, strikes, network outages, infrastructure failures, courier disruption, or other extraordinary events.'),
    section('20. Applicable Law and Contact', 'These Terms are intended to operate consistently with applicable Indian law and consumer-protection requirements. Nothing removes a right or remedy that cannot legally be excluded. For questions, contact HILOL Support through the website.')
  ] as LegalSection[] },
  privacy: { eyebrow: 'LEGAL / PRIVACY', title: 'PRIVACY, WITHOUT THE WEIRDNESS.', lede: 'At HILOL, we collect and use information mainly to do one thing: get your order to you and help when something goes wrong. This Privacy Policy explains what information we collect, why we use it, when it may be shared, and the choices available to you. Last updated: 2026.', sections: [
    section('1. What We Collect', 'Depending on how you use HILOL, we may collect your name, phone number, email address, shipping and billing information, order details including products, sizes, colours, quantities and status, payment-related transaction information, support messages, account information, and information voluntarily provided through forms, feedback, reviews, or other website features.'),
    section('2. Why We Use Your Information', 'We use information to process and fulfill orders; confirm and communicate about orders; arrange printing, packaging, and delivery; provide support; handle cancellations, replacements, refunds, and disputes; verify transactions; prevent fraud or misuse; maintain and improve the website; communicate important service information; comply with legal, regulatory, accounting, or record-keeping requirements; and protect HILOL, customers, and services.'),
    section('3. Payments', 'Payments may be processed through Cashfree or another provider made available by HILOL. HILOL does not intentionally store full card numbers, card security codes, UPI PINs, banking passwords, or payment passwords. We may receive payment status, transaction identifiers, and related order information.'),
    section('4. Sharing Information', 'We may share information reasonably necessary with payment providers, fulfillment and production partners, courier providers, technology or hosting providers, customer-support providers, security or fraud-prevention services, and authorities where required or permitted by law. We do not sell personal information.'),
    section('5. Cookies and Similar Technologies', 'HILOL may use cookies, local storage, analytics tools, or similar technologies to keep the website functioning, remember preferences, understand usage, improve performance, and support essential features. Disabling them may affect functionality.'),
    section('6. Security and Retention', 'We use reasonable safeguards including HTTPS-secured connections, access controls, limited access, authentication, and operational safeguards. No online transmission can be guaranteed completely secure. We retain information only as reasonably necessary for orders, support, disputes, fraud prevention, and legal, tax, accounting, or regulatory requirements.'),
    section('7. Your Choices', 'Subject to applicable law and necessary retention, you may request access to, correction of, or deletion of personal information where legally available, or ask how information is handled. Some information must be retained by law or for legitimate transaction-related purposes.'),
    section('8. Other People and Children', 'If you provide another person’s information, you should have permission or authority to do so. HILOL is not specifically directed toward children. Where required, a parent or legal guardian should be involved.'),
    section('9. Legal Requirements and Changes', 'We may access, preserve, or disclose information to comply with law, respond to lawful requests, enforce policies, investigate fraud or abuse, and protect rights, safety, or property. We may update this policy and its Last updated date when practices, technology, or legal requirements change.'),
    section('10. Contact Us', 'For privacy questions or requests, contact HILOL Support through the official contact details available on the website.')
  ] as LegalSection[] },
  shipping: { eyebrow: 'POLICY / SHIPPING', title: 'SHIPPING. GET IT. WEAR IT.', lede: 'We offer standard delivery on all eligible orders, with an optional express upgrade available at checkout. Delivery times are estimates and can vary depending on location, courier serviceability, weather, holidays, and other circumstances outside HILOL’s reasonable control. Last updated: 2026.', sections: [
    section('1. Standard Delivery', 'Standard delivery is included in the displayed product price for eligible orders. Orders use Delhivery Surface. Estimated delivery is 4–5 days after dispatch, depending on location and courier serviceability. Remote, difficult-to-service, or restricted locations may take longer. The estimate is not guaranteed.'),
    section('2. Express Delivery', 'Express is an optional ₹40 upgrade where serviceability permits. Orders use BlueDart Express Air and may arrive approximately 1–2 days faster than Standard. Express does not guarantee a particular date or time and may not appear for an unsupported PIN code.'),
    section('3. When Delivery Time Starts', 'Delivery estimates refer to the courier delivery period and not necessarily the exact time from placing an order. Processing, production, packing, and courier pickup may take additional time before transit begins.'),
    section('4. Tracking', 'Tracking is provided when available and may take time to become active after dispatch. Use the tracking information supplied by HILOL. If it does not update for an unusually long period, contact Support.'),
    section('5. Delivery Address', 'Check your name, phone number, house or building number, street or locality, city, state, and PIN code before ordering. HILOL cannot be responsible for delivery problems caused by incorrect or incomplete information, except where applicable law provides otherwise.'),
    section('6. Courier Delays', 'Weather, public holidays, high shipment volumes, traffic or transport disruption, remote serviceability, incorrect information, unsuccessful attempts, natural events, government restrictions, and other circumstances outside HILOL’s reasonable control can affect delivery.'),
    section('7. Delivery Attempts', 'Keep your phone available and cooperate with reasonable delivery requirements. If an attempt fails because the recipient is unavailable, the address is incorrect, or the package is refused or cannot be accepted, further attempts or return-to-origin procedures may apply.'),
    section('8. Lost, Missing, or Undelivered Orders', 'If an order has not arrived within a reasonable period after the expected window, contact Support. We may work with the courier to investigate. The applicable remedy is handled under the Refund and Replacement Policy and applicable law.'),
    section('9. Damaged Packages', 'Document a damaged package as soon as reasonably possible and contact Support if there is an issue with the product. HILOL may request photographs, videos, or other relevant information.'),
    section('10. Remote Locations and Express Refunds', 'Some PIN codes may have longer delivery times, limited options, additional restrictions, or no service. Express delays do not automatically guarantee compensation or an Express-fee refund. Any remedy is determined under the applicable policy and law.'),
    section('11. Contact Support', 'For a delivery problem, include your order number, name, phone number or email used for the order, and tracking information if available. We will review the situation and help with the applicable next step.')
  ] as LegalSection[] },
  refunds: { eyebrow: 'POLICY / RETURNS', title: 'REFUNDS. WHEN SOMETHING ACTUALLY GOES WRONG.', lede: 'HILOL products are made to order. Because each garment is produced specifically for an order, we do not accept ordinary returns or exchanges simply because someone changes their mind or chooses the wrong size. If we make a fulfillment or manufacturing mistake, we will make it right. Last updated: 2026.', sections: [
    section('1. Cancellation Window', 'You may request cancellation within 60 minutes of placing your order, provided printing has not begun. After 60 minutes or once printing has begun, the order cannot ordinarily be cancelled or changed. Cancellation requests are subject to the Cancellation Policy and applicable law.'),
    section('2. When a Replacement May Be Available', 'Contact HILOL within 24 hours of delivery if an item is damaged when received, genuinely defective due to manufacturing, incorrectly printed, printed with the wrong design, the wrong product, the wrong size or colour due to a HILOL fulfillment error, or missing from your order. A verified issue may receive a replacement or reprint at no additional product cost.'),
    section('3. Your Unboxing Video May Be Required', 'For certain claims HILOL may require a continuous, uncut 360° unboxing video. It should begin with the package sealed, show the shipping label, show the package opening continuously, show contents being removed, and show all contents. Claims requiring evidence must be submitted within 24 hours.'),
    section('4. What Is Not Eligible', 'We do not normally accept returns, replacements, or refunds for change of mind, wrong size, wrong colour, wrong design, wrong quantity, normal wear, incorrect washing or care, misuse, customer alterations, customer-caused damage, or minor variations within reasonable industry tolerances. Check the Size Guide before ordering.'),
    section('5. Size Selection and Manufacturing Variations', 'Compare the measurements with a garment you own before ordering. A customer selecting the wrong size is not ordinarily a fulfillment error. Small variations in measurements, placement, colour appearance, or other manufacturing characteristics do not automatically constitute a defect.'),
    section('6. Courier Damage and Lost Orders', 'If a package arrives damaged or appears tampered with, document it and contact Support. If an order has not arrived within a reasonable period after the expected window, contact Support so HILOL can investigate with the delivery provider.'),
    section('7. Refunds', 'Because products are made to order, monetary refunds are not the default remedy for verified product defects or fulfillment errors. The normal resolution may be a replacement or reprint. Where a monetary refund is required or appropriate under applicable law or the circumstances, HILOL will process it through the appropriate payment method.'),
    section('8. Return Shipping', 'For a confirmed HILOL fulfillment or manufacturing error, HILOL may arrange or cover applicable return shipping where required. Customer-selection or customer-use issues generally do not qualify for covered return shipping.'),
    section('9. How to Make a Claim', 'Contact Support within 24 hours of delivery with your order number, contact details, description of the issue, clear photographs, and an uncut 360° video if requested. Do not throw away the product or packaging until review.'),
    section('10. Claim Review', 'Every claim is reviewed based on the information and circumstances provided. We may request additional reasonable evidence. Submitting a claim does not automatically guarantee approval.'),
    section('11. No Change-of-Mind Returns', 'Because products are made to order specifically for customers, we do not accept ordinary returns simply because you do not like the product, changed your mind, ordered the wrong size or colour, selected the wrong design, or no longer want it. So yeah — check the size chart before you cook your own order.'),
    section('12. Policy and Applicable Law', 'This policy is intended to operate consistently with applicable Indian consumer-protection laws. Nothing removes or restricts a consumer right or remedy that cannot legally be excluded. Where applicable law provides a mandatory remedy that differs from this policy, the applicable law prevails.'),
    section('13. Contact Support', 'For any return, replacement, refund, or order issue, use the Support link on the HILOL website and include your order number.')
  ] as LegalSection[] },
  cancellation: { eyebrow: 'POLICY / CANCELLATION', title: 'CANCELLATION. BEFORE IT GOES INTO PRODUCTION.', lede: 'HILOL products are made to order, so orders can enter production quickly. Because of this, our cancellation window is intentionally short. Last updated: 2026.', sections: [
    section('1. 60-Minute Cancellation Window', 'You may request cancellation within 60 minutes of placing your order, provided printing has not already begun. After 60 minutes, or once printing has begun, the order generally cannot be cancelled or changed, including product, meme or design, size, colour, quantity, delivery information, or other order details.'),
    section('2. Cancellation Is a Request', 'Submitting a cancellation request does not automatically cancel your order. Cancellation is confirmed only when HILOL confirms that the order has been successfully cancelled. Until then, the order remains active.'),
    section('3. How to Request Cancellation', 'Contact HILOL Support through the Support link and provide your order number, name used for the order, phone number or email associated with the order, and a clear request to cancel. Contact us as soon as possible rather than waiting until the end of the window.'),
    section('4. COD Orders', 'For Cash on Delivery orders, ₹80 is paid upfront and the remaining amount at delivery. If an eligible cancellation is confirmed within 60 minutes and before printing begins, the full ₹80 upfront payment will be refunded, no remaining COD amount will be collected, and the refund will use the applicable payment method.'),
    section('5. Prepaid Orders', 'For prepaid orders, an eligible cancellation confirmed within the 60-minute window will be processed for the applicable refund. Refund timing may vary by payment provider or financial institution.'),
    section('6. After the Cancellation Window', 'Once the 60-minute window has passed or printing has begun, HILOL generally cannot cancel or modify the order. This includes wrong size, meme, colour, address, or other details. Contact Support immediately if you notice an error, but changes are not guaranteed.'),
    section('7. If HILOL Cancels an Order', 'HILOL may cancel for product availability issues, obvious pricing or technical errors, incomplete or unusable information, an unserviceable location, payment problems, suspected fraudulent or abusive activity, or circumstances outside reasonable control. Applicable refunds will follow law and relevant policies.'),
    section('8. Refusing Delivery Is Not Cancellation', 'Refusing or ignoring delivery after an order has entered fulfillment or transit does not count as a cancellation request. Failed deliveries, refused COD orders, and returned shipments may be handled under applicable HILOL policies.'),
    section('9. Applicable Law', 'This policy is intended to operate consistently with applicable Indian consumer-protection laws. Nothing removes or restricts a consumer right or remedy that cannot legally be excluded. Where applicable law requires a different outcome, applicable law prevails.'),
    section('10. Need to Cancel?', 'Don’t wait. Contact HILOL Support as soon as possible after placing your order. Your cancellation is complete only when HILOL confirms it.')
  ] as LegalSection[] }
} as const

export type LegalKey = keyof typeof legalContent
